# The URL the site will be built for (update to your real domain in prod)
base_url = "http://127.0.0.1:1111"
title = "VicBlog"
theme = "goyo"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"
smart_punctuation = true

[extra]
# Put all your custom variables here
katex = true
mermaid = true
logo_text = "Goyo"
logo_image_path = "images/goyo.png"
logo_image_padding = "5px"
footer_html = "Powered by <a href='https://www.getzola.org'>Zola</a> and <a href='https://github.com/hahwul/goyo'>Goyo</a>"
default_thumbnail = "images/default_thumbnail.jpg"
twitter_site = "@hahwul"
twitter_creator = "@hahwul"
default_colorset = "dark"
brightness = "normal"
gtag = ""
sidebar_expand_depth = 1
lang_aliases = { en = "English", ko = "한국어" }
disable_theme_toggle = false
disable_root_sidebar_hide = false
edit_url = ""
nav = [
  { name = "Engineering", url = "/engineering/", type = "url", icon = "fa-solid fa-gear" },
  { name = "Math", url = "/math/", type = "url", icon = "fa-solid fa-square-root-variable" },
  { name = "Essays", url = "/essays/", type = "url", icon = "fa-solid fa-scale-balanced" },
  { name = "About", url = "/about/", type = "url", icon = "fa-solid fa-user" },
]

[extra.comments]
enabled = false
system = ""
repo = ""
repo_id = ""
category = ""
category_id = ""

# Taxonomies
[[taxonomies]]
name = "tags"


[[taxonomies]]
name = "categories"


[search]
index_format = "elasticlunr_json"
include_title = true
include_description = true
include_content = true
